# Generated by Django 6.0.4 on 2026-04-08 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unit_of_measurement', models.CharField(help_text='e.g., kg, grams, pieces, liters', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit of measurement (in pesos)', max_digits=10)),
                ('date_bought', models.DateField(auto_now_add=True, help_text='Date the ingredient price was manually logged from the market')),
                ('source', models.CharField(default='Manual Input', help_text='e.g. Manual Input or OCR Receipt', max_length=100)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.ingredient')),
            ],
            options={
                'ordering': ['-date_bought'],
            },
        ),
    ]
