# Generated by Django 6.0.4 on 2026-04-08 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, help_text="Calculated cost of all ingredients based on today's market price", max_digits=10)),
                ('actual_profit_margin_percentage', models.DecimalField(decimal_places=2, help_text='Calculated actual profit margin % based on selling price vs total cost', max_digits=5)),
                ('date_calculated', models.DateField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_snapshots', to='menu.menuitem')),
            ],
            options={
                'ordering': ['-date_calculated'],
            },
        ),
    ]
