# Generated by Django 6.0.4 on 2026-04-08 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('Recommendation', 'Recommendation'), ('Warning', 'Warning'), ('Action Taken', 'Action Taken')], max_length=50)),
                ('suggested_action', models.CharField(choices=[('Increase Price', 'Increase Price'), ('Maintain Price (Monitor)', 'Maintain Price (Monitor)'), ('Decrease Price', 'Decrease Price')], max_length=50)),
                ('reasoning', models.TextField(help_text="Explanation: e.g., 'Ribeye Beef rose by 10% this week, dropping your profit margin to 8%.'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='menu.menuitem')),
            ],
        ),
    ]
